### PR TITLE
Update AAD Token V2

### PR DESCRIPTION
**Pull request by kritchaponc**
Add Method for GET AAD Token for Azure AAD OAuth V2 by replacing resource to scope

### CODE REVIEW

**Comment by larshp** [comment]
https://github.com/microsoft/ABAP-SDK-for-Azure/pull/94 handles the 2 issues with OCCURS

**Comment by kritchaponc** [comment]
There're some services like Service Now that require Azure AD Connect V2.0. Currently, this SDK only support V1.0 so I create the new method and change a few parameter from resource (v1) to scope (v2).

**Comment by kritchaponc** [comment]
Need to redefine and add some enhancement so decide to close the PR for now.

**Comment by kritchaponc** [comment]
@larshp Hi Lars Hvam,

Is it possible to merge this PR into main branch ? Currently many service required AAD Token version 2 and changes include 
1. Clone Get AAD Token method
2. Change Parameter name from resource -> scope.
Or if there are anything I have to provide can you give me a suggestion?
Best Regards,

**Comment by larshp** [comment]
I dont have access, I'm not a maintainer of this repo

**Comment by vikasbansal2022** [comment]
Thanks @kritchaponc for making contribution to the Repo.

Instead of changing the code and changing the Resource to scope.  you can setup RFC connection with OAUTH2 URL and ZCL_ADF_SERVICE_AAD~GET_AAD_TOKEN will be the token. 

Please let me know if you have any other thoughts.
 

image

**Pull request closed without merging**
