### PR TITLE
Azure graph support

### PR DESCRIPTION
**Pull request by gregorwolf**

### CODE REVIEW

**Comment by krdash** [comment]
Hello Gregor, @gregorwolf 
Thanks for contributing. We appreciate your effort.
Its great to see that Azure Graph API library is part of SDK now. We will be testing these changes in our new staging environment and merge the same into the master branch after successfull testing.
Thanks,
Krishna

**Comment by krdash** [comment]
@gregorwolf - Hello Gregor, we see that table maintenance regeneration has removed some validation code from table maintenance screen for table ZADF_CONFIG . Request you to look into this and synch it with the original table maintenance view code of master branch along with the changes of extending service domain for Azure-graph support and please commit the same.
Module which has been removed as shown below.
MODULE validate_saskey
Thanks, Krishna

**Comment by matt1as** [comment]
Hi,

This PR tries to create the below objects directly under the main package, it is not possible to pull and activate it.

````
TABL	ZADF_SERVICE_GRAPH_PASSWORDPRO	
TABL	ZADF_SERVICE_GRAPH_SIGNINNAME
TABL	ZADF_SERVICE_GRAPH_USER
TTYP	ZADF_SERVICE_GRAPH_SIGNINNAM_T
````

**Comment by gregorwolf** [comment]
Please try again @matt1as as I moved the files to the correct package folder

**Comment by gregorwolf** [comment]
@krdash I've removed the changes on the generated function group. Can you now please merge.

**Pull request merged**
