### PR TITLE
update pipelines

### PR DESCRIPTION
**Pull request by larshp**
this will publish the results under tests in the pipleline

example: https://larshvam.visualstudio.com/github/_build/results?buildId=11&view=ms.vss-test-web.build-test-results-tab

### CODE REVIEW

**Comment by larshp** [comment]
also consider if you want to run both Azure Pipelines and abaplint.org

note that abaplint.org gives the best integration with github via https://github.com/Microsoft/ABAP-SDK-for-Azure/pull/37/checks, no need to nagivate to external page to show results

however it looks like there is some bug, so it currently reports 0 findings, might take a look sometime during the weekend

**Comment by NaveenKurmadas** [comment]
> also consider if you want to run both Azure Pipelines and abaplint.org it runs the same code/checks
> 
> note that abaplint.org gives the best integration with github via https://github.com/Microsoft/ABAP-SDK-for-Azure/pull/37/checks, no need to nagivate to external page to show results
> 
> however it looks like there is some bug, so it currently reports 0 findings, might take a look sometime during the weekend

I'm evaluating all the pipelines. Eventually we will have only Azure pipeline active for Abap-sdk-for-Azure.

**Comment by larshp** [comment]
cool

just want to note the feature for abaplint.org using Github Checks API, so the errors found are shown directly in the code on github, example https://github.com/larshp/abapGit/commit/b4aa894decb562982d92e62c87b613203e6616f3#annotation_19981662

**Comment by NaveenKurmadas** [comment]
that's a cool feature. Any idea if the same feature can be extended to Azure pipelines? and also, how to enable this feature through abaplint.org, any documentation or reference will help. Thanks.

**Comment by larshp** [comment]
for abaplint.org it is enabled by default, however, as noted above I think there is a bug, currently, abaplint.org shows 0 errors for this repo, I'll take a look at it sometime during the weekend

Azure, it can, its just work, you can take a look at the GitHub Actions example, https://github.com/abaplint/actions-abaplint, how to send the results to the Checks API

**Comment by larshp** [comment]
abaplint.org issue fixed

**Comment by NaveenKurmadas** [comment]
@larshp Thanks

**Pull request merged**
